### ISSUE TITLE
Error filestem is not defined after initial npm install and run 

### ISSUE THREAD

**Issue by xdcha** [locomotivemtl/locomotive-boilerplate#125]
Hello. <3 the boilerplate, however, on `npm start` for the first time I am hit with an error: 

```
file:///Volumes/e/build/tasks/styles.js:234
    const timeLabel = `${filestem}.css purged in`;
                      ^

ReferenceError: filestem is not defined
    at purgeUnusedCSS (file:///Volumes/e/build/tasks/styles.js:234:23)
    at file:///Volumes/e/build/tasks/styles.js:149:25
    at async file:///Volumes/e/build/tasks/styles.js:146:17
```

Many thanks

**Comment by mcaskill** [comment]
Thanks
